In [2]:
import torch 
import numpy as np 

In [3]:
matrix = torch.tensor([1,2,3])

In [4]:
matrix

tensor([1, 2, 3])

In [5]:
example_matrix2=torch.tensor([[1,2,3],
                             [4,5,6],
                             [7,8,9]
                             ])


In [6]:
example_matrix2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
matrix * example_matrix2

tensor([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]])

In [8]:
example_matrix2 @ example_matrix2

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
torch.matmul(example_matrix2 , example_matrix2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [10]:
tensor1 = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

In [11]:
tensor2 = torch.tensor([
    [7,8],
    [9,10],
    [11,12]
])

In [12]:
tensor1.shape

torch.Size([3, 2])

In [13]:
tensor2.shape

torch.Size([3, 2])

In [14]:
torch.matmul(tensor1,tensor2.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [15]:
tensor2.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [16]:
tensor2.T.shape

torch.Size([2, 3])

In [17]:
tensor1 @ tensor2.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [18]:
A = torch.tensor([[1,2,3]])

In [19]:
A.shape

torch.Size([1, 3])

In [20]:
A.ndim

2

In [21]:
B = torch.tensor([[4],[5],[6]])

In [22]:
B.shape

torch.Size([3, 1])

In [23]:
B.ndim

2

In [24]:
A @ B

tensor([[32]])

In [25]:
result = A @ B

In [26]:
result.shape

torch.Size([1, 1])

In [27]:
result.ndim

2