In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.arange(0,50,5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
tensor.min()

tensor(0)

In [5]:
tensor.max()

tensor(45)

In [6]:
tensor.sum()

tensor(225)

In [7]:
tensor.median()

tensor(20)

In [8]:
tensor = tensor.type(torch.float)

In [9]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [10]:
tensor.mean()

tensor(22.5000)

In [11]:
# argmax , argmin

In [12]:
tensor.max()

tensor(45.)

In [13]:
tensor.argmax()

tensor(9)

In [14]:
tensor.min()

tensor(0.)

In [15]:
tensor.argmin()

tensor(0)

In [16]:
tensor[9]

tensor(45.)

In [17]:
tensor[5]

tensor(25.)

In [18]:
matrix = torch.tensor([[10,20,30],[40,50,60]])

In [19]:
matrix.argmax()

tensor(5)

In [20]:
matrix[1][2]

tensor(60)

In [21]:
matrix[:,1]

tensor([20, 50])

In [22]:
matrix[0,1]

tensor(20)

In [26]:
# manipulating tensor : reshaping,stacking,squeezing,unsqueezing

In [27]:
x = torch.arange(1,10,1)

In [28]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x.shape

torch.Size([9])

In [30]:
x.ndim

1

In [33]:
x_reshaped = x.reshape(1,9)

In [34]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
x_reshaped.shape

torch.Size([1, 9])

In [36]:
x_reshaped.ndim

2

In [41]:
y = torch.randn(224,224,3)

In [42]:
y

tensor([[[-1.1318, -0.6317,  0.8764],
         [-2.3407,  0.3355,  0.0960],
         [ 1.0749, -1.4205,  0.7406],
         ...,
         [ 0.0985, -0.8941,  0.6161],
         [-1.0316, -0.2095, -0.7342],
         [ 0.4117, -2.1466,  1.7316]],

        [[ 1.8540, -1.7265,  0.9186],
         [ 2.1505,  1.4489, -0.0096],
         [-0.7728, -0.5431,  1.1356],
         ...,
         [ 0.8019, -0.7613, -0.0279],
         [ 0.1369,  1.5516, -1.4301],
         [-0.3538, -0.5059, -0.1136]],

        [[ 0.9156, -1.1301, -0.3952],
         [-0.3750,  2.0086, -0.0467],
         [-1.0707, -0.6235, -0.2113],
         ...,
         [-0.4742, -1.6259,  1.2042],
         [-0.6105,  1.2267,  1.2986],
         [-0.2825, -2.3574,  1.6986]],

        ...,

        [[-1.4222,  0.4313, -0.8511],
         [-0.7817, -0.0820, -1.7021],
         [ 1.4465,  0.3757,  0.2615],
         ...,
         [ 0.8743, -0.4099,  1.4062],
         [-0.5354,  1.4767, -0.2304],
         [ 0.2056, -3.1928, -0.2115]],

        [[

In [43]:
y.shape

torch.Size([224, 224, 3])

In [44]:
y.ndim

3

In [45]:
x_reshaped = x.reshape(3,3)

In [46]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x_reshaped.shape

torch.Size([3, 3])

In [49]:
x_reshaped.ndim

2

In [50]:
x_reshaped = x_reshaped.reshape(9,1)

In [51]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [53]:
#  x_reshaped = x_reshaped.reshape(2,3) The product of the two numbers we provide must be equal to the number of elements.

In [54]:
# viev

In [55]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [56]:
x_reshaped[2] = 20

In [57]:
x_reshaped

tensor([[ 1],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [60]:
x_reshaped.argmax()

tensor(2)

In [61]:
x_reshaped.argmin()

tensor(0)

In [62]:
x

tensor([ 1,  2, 20,  4,  5,  6,  7,  8,  9])

In [63]:
x_view = x_reshaped.view(9,1)

In [64]:
x_view

tensor([[ 1],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [65]:
x_view[0] = 10

In [66]:
x_view

tensor([[10],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [67]:
x

tensor([10,  2, 20,  4,  5,  6,  7,  8,  9])

In [68]:
# view -> contigious tensor 

In [69]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])

In [70]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
x.is_contiguous()

True

In [73]:
y = x.t()

In [74]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [76]:
y.is_contiguous()

False

In [77]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [ ]:
# y.view(1,6) --> This code won't work because view() only works on contiguous tensors.

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [83]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [ ]:
x=torch.arange(24)

In [87]:
y=x.reshape(2,3,4)

In [88]:
y

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [89]:
y.shape

torch.Size([2, 3, 4])