In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.arange(0,50,5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
tensor.min()

tensor(0)

In [5]:
tensor.max()

tensor(45)

In [6]:
tensor.sum()

tensor(225)

In [7]:
tensor.median()

tensor(20)

In [8]:
tensor = tensor.type(torch.float)

In [9]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [10]:
tensor.mean()

tensor(22.5000)

In [11]:
# argmax , argmin

In [12]:
tensor.max()

tensor(45.)

In [13]:
tensor.argmax()

tensor(9)

In [14]:
tensor.min()

tensor(0.)

In [15]:
tensor.argmin()

tensor(0)

In [16]:
tensor[9]

tensor(45.)

In [17]:
tensor[5]

tensor(25.)

In [18]:
matrix = torch.tensor([[10,20,30],[40,50,60]])

In [19]:
matrix.argmax()

tensor(5)

In [20]:
matrix[1][2]

tensor(60)

In [21]:
matrix[:,1]

tensor([20, 50])

In [22]:
matrix[0,1]

tensor(20)

In [26]:
# manipulating tensor : reshaping,stacking,squeezing,unsqueezing

In [27]:
x = torch.arange(1,10,1)

In [28]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x.shape

torch.Size([9])

In [30]:
x.ndim

1

In [33]:
x_reshaped = x.reshape(1,9)

In [34]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
x_reshaped.shape

torch.Size([1, 9])

In [36]:
x_reshaped.ndim

2

In [41]:
y = torch.randn(224,224,3)

In [42]:
y

tensor([[[-1.1318, -0.6317,  0.8764],
         [-2.3407,  0.3355,  0.0960],
         [ 1.0749, -1.4205,  0.7406],
         ...,
         [ 0.0985, -0.8941,  0.6161],
         [-1.0316, -0.2095, -0.7342],
         [ 0.4117, -2.1466,  1.7316]],

        [[ 1.8540, -1.7265,  0.9186],
         [ 2.1505,  1.4489, -0.0096],
         [-0.7728, -0.5431,  1.1356],
         ...,
         [ 0.8019, -0.7613, -0.0279],
         [ 0.1369,  1.5516, -1.4301],
         [-0.3538, -0.5059, -0.1136]],

        [[ 0.9156, -1.1301, -0.3952],
         [-0.3750,  2.0086, -0.0467],
         [-1.0707, -0.6235, -0.2113],
         ...,
         [-0.4742, -1.6259,  1.2042],
         [-0.6105,  1.2267,  1.2986],
         [-0.2825, -2.3574,  1.6986]],

        ...,

        [[-1.4222,  0.4313, -0.8511],
         [-0.7817, -0.0820, -1.7021],
         [ 1.4465,  0.3757,  0.2615],
         ...,
         [ 0.8743, -0.4099,  1.4062],
         [-0.5354,  1.4767, -0.2304],
         [ 0.2056, -3.1928, -0.2115]],

        [[

In [43]:
y.shape

torch.Size([224, 224, 3])

In [44]:
y.ndim

3

In [45]:
x_reshaped = x.reshape(3,3)

In [46]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x_reshaped.shape

torch.Size([3, 3])

In [49]:
x_reshaped.ndim

2

In [50]:
x_reshaped = x_reshaped.reshape(9,1)

In [51]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [53]:
#  x_reshaped = x_reshaped.reshape(2,3) The product of the two numbers we provide must be equal to the number of elements.

In [54]:
# viev

In [55]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [56]:
x_reshaped[2] = 20

In [57]:
x_reshaped

tensor([[ 1],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [60]:
x_reshaped.argmax()

tensor(2)

In [61]:
x_reshaped.argmin()

tensor(0)

In [62]:
x

tensor([ 1,  2, 20,  4,  5,  6,  7,  8,  9])

In [63]:
x_view = x_reshaped.view(9,1)

In [64]:
x_view

tensor([[ 1],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [65]:
x_view[0] = 10

In [66]:
x_view

tensor([[10],
        [ 2],
        [20],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [67]:
x

tensor([10,  2, 20,  4,  5,  6,  7,  8,  9])

In [68]:
# view -> contigious tensor 

In [69]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])

In [70]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
x.is_contiguous()

True

In [73]:
y = x.t()

In [74]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [76]:
y.is_contiguous()

False

In [77]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [98]:
# y.view(1,6) --> This code won't work because view() only works on contiguous tensors.

In [83]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [92]:
tensor1=torch.arange(24)

In [93]:
tensor2 = tensor1.reshape(2,3,4)

In [94]:
tensor2

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [95]:
tensor2.shape

torch.Size([2, 3, 4])

In [90]:
# stacking

In [100]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])

In [101]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [105]:
torch.stack([x,x,x,x] ,dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [106]:
torch.stack([x,x,x,x] ,dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [107]:
# squeeze & unsqueeze

In [108]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [109]:
x.shape

torch.Size([2, 3])

In [110]:
x.ndim

2

In [111]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [116]:
x = torch.tensor([[1,2,3]])

In [120]:
x.ndim

2

In [121]:
x.shape

torch.Size([1, 3])

In [117]:
x.squeeze()

tensor([1, 2, 3])

In [118]:
x.squeeze().shape

torch.Size([3])

In [119]:
x.squeeze().ndim

1

In [125]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [126]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.unsqueeze(dim=0)

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [131]:
y= x.unsqueeze(dim=0)

In [133]:
y.ndim

3

In [134]:
x.ndim

2

In [135]:
y.shape

torch.Size([1, 2, 3])

In [136]:
z= y.unsqueeze(dim=0)

In [137]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [138]:
z.ndim

4

In [139]:
z.shape

torch.Size([1, 1, 2, 3])

In [140]:
t = z.squeeze()

In [141]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [142]:
t.ndim

2

In [143]:

t.shape

torch.Size([2, 3])

In [148]:
x=torch.tensor([[1],[2],[3]])


In [149]:
x.shape

torch.Size([3, 1])

In [152]:
y =x.squeeze()

In [153]:
y

tensor([1, 2, 3])

In [154]:
# permute

In [155]:
x = torch.rand(size=(224,224,3))

In [156]:
x

tensor([[[0.3877, 0.1097, 0.8455],
         [0.4169, 0.4066, 0.2113],
         [0.2982, 0.4307, 0.9045],
         ...,
         [0.3861, 0.5818, 0.0100],
         [0.0818, 0.6001, 0.3150],
         [0.5105, 0.7660, 0.5495]],

        [[0.2614, 0.0777, 0.2762],
         [0.4736, 0.5624, 0.2823],
         [0.3471, 0.8574, 0.3486],
         ...,
         [0.9015, 0.8347, 0.5258],
         [0.6036, 0.9492, 0.3060],
         [0.7210, 0.4090, 0.0166]],

        [[0.4569, 0.3290, 0.6306],
         [0.9084, 0.3331, 0.9538],
         [0.1149, 0.7592, 0.5962],
         ...,
         [0.8620, 0.6110, 0.7412],
         [0.2323, 0.5742, 0.5105],
         [0.1594, 0.4545, 0.1618]],

        ...,

        [[0.7305, 0.5755, 0.0961],
         [0.2303, 0.3872, 0.0643],
         [0.6792, 0.0126, 0.4117],
         ...,
         [0.7755, 0.3797, 0.3572],
         [0.5099, 0.9907, 0.4328],
         [0.2285, 0.7635, 0.2884]],

        [[0.8253, 0.8897, 0.9475],
         [0.3171, 0.8138, 0.8639],
         [0.

In [157]:
x.shape

torch.Size([224, 224, 3])

In [158]:
x_permuted = x.permute(2,0,1) # axis 0-->1 , 1-->2 , 2 -->0

In [160]:
x_permuted.shape

torch.Size([3, 224, 224])

In [161]:
y = torch.rand(size=(5,8,9))

In [162]:
y_permuted = y.permute(1,2,0)

In [164]:
y_permuted.shape

torch.Size([8, 9, 5])

In [165]:
# indexing & slicing

In [166]:
a = torch.arange(1,10,1)

In [167]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
a = a.reshape(1,3,3)

In [171]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [174]:
a[0][0][0]

tensor(1)

In [175]:
a[:,0,1]

tensor([2])

In [176]:
a[:,2,1]

tensor([8])

In [177]:
a[:,:,2]

tensor([[3, 6, 9]])

In [178]:
a[:,1,:]

tensor([[4, 5, 6]])

In [179]:
x = torch.tensor([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [180]:
x[1:, 0:2]

tensor([[40, 50],
        [70, 80]])

In [182]:


x = torch.arange(16).reshape(4,4)



In [183]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [184]:
print(x[1:3, 2:4])

tensor([[ 6,  7],
        [10, 11]])


In [185]:
# random seed

In [186]:
random_tensor = torch.rand(3,4)

In [187]:
random_tensor

tensor([[0.2036, 0.3033, 0.7409, 0.8087],
        [0.0074, 0.7067, 0.0360, 0.5704],
        [0.0173, 0.2366, 0.3000, 0.3800]])

In [191]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(3,4)
random_tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [193]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(3)
random_tensor1

tensor([0.8823, 0.9150, 0.3829])