In [29]:
import torch
import numpy as np

In [30]:
tensor = torch.arange(0,50,5)

In [31]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
tensor.min()

tensor(0)

In [33]:
tensor.max()

tensor(45)

In [34]:
tensor.sum()

tensor(225)

In [35]:
tensor.median()

tensor(20)

In [36]:
tensor = tensor.type(torch.float)

In [37]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [38]:
tensor.mean()

tensor(22.5000)

In [39]:
# argmax , argmin

In [40]:
tensor.max()

tensor(45.)

In [41]:
tensor.argmax()

tensor(9)

In [42]:
tensor.min()

tensor(0.)

In [43]:
tensor.argmin()

tensor(0)

In [44]:
tensor[9]

tensor(45.)

In [45]:
tensor[5]

tensor(25.)

In [46]:
matrix = torch.tensor([[10,20,30],[40,50,60]])

In [28]:
matrix.argmax()

tensor(5)

In [47]:
matrix[1][2]

tensor(60)

In [48]:
matrix[:,1]

tensor([20, 50])

In [49]:
matrix[0,1]

tensor(20)