In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.backends.mps.is_available()

False

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
device

'cuda'

In [7]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [8]:
device

'cuda'

In [9]:
tensor = torch.tensor([1,2,3])

In [10]:
tensor

tensor([1, 2, 3])

In [11]:
tensor.device

device(type='cpu')

In [12]:
# manual

In [13]:
tensor_on_gpu = tensor.to(device)

In [14]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [17]:
tensor.numpy()

array([1, 2, 3])

In [20]:
#tensor_on_gpu.numpy()

In [21]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [22]:
# context manager

In [26]:
with torch.device("cuda"):
    tensor2 = torch.tensor([1,2,3])
    layer =torch.nn.Linear(20,30)



In [27]:
tensor2.device

device(type='cuda', index=0)

In [28]:
layer.weight.device

device(type='cuda', index=0)

In [29]:
tensor3 = torch.tensor([4,5,6])

In [30]:
tensor3.device

device(type='cpu')

In [31]:
# torch.set_default_device

In [32]:
device

device(type='cuda')

In [33]:
torch.set_default_device(device)

In [34]:
tensor4 = torch.tensor([7,8,9])
layer2 = torch.nn.Linear(40,50)

In [35]:
tensor4.device

device(type='cuda', index=0)

In [36]:
layer2.weight.device

device(type='cuda', index=0)

In [37]:
tensor3.device

device(type='cpu')