In [2]:
import torch
import numpy as np 

In [3]:
random_array = np.random.randn(3,5)

In [4]:
random_array

array([[ 1.25273089,  0.40885296, -1.93069036,  0.23652185, -0.56118331],
       [-0.16311302,  0.6294964 ,  0.36295088, -0.47949219,  1.1197813 ],
       [ 0.32911469, -0.43268584,  0.16284663, -0.12255331, -1.24379805]])

In [5]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

In [7]:
random_matrix = torch.rand(size=(3,5))

In [8]:
random_matrix

tensor([[0.0350, 0.8727, 0.0049, 0.6465, 0.1405],
        [0.1648, 0.3372, 0.1975, 0.0264, 0.0923],
        [0.0139, 0.8219, 0.5386, 0.7784, 0.4641]])

In [9]:
random_matrix.ndim

2

In [10]:
random_matrix.shape

torch.Size([3, 5])

In [11]:
random_matrix.dtype

torch.float32

In [12]:
random_tensor = torch.randn(size = (224,224,3))

In [13]:
random_tensor

tensor([[[-0.6346, -0.4036,  0.2035],
         [-1.4241,  0.0885,  0.8211],
         [-0.9390, -1.5437, -0.3639],
         ...,
         [ 0.9369, -2.2998, -0.0096],
         [ 0.8974, -0.6239, -2.0531],
         [-0.7865,  0.0565, -0.2574]],

        [[ 1.3921,  0.6939,  0.3362],
         [-2.0880,  0.7310, -0.1924],
         [-1.1166,  1.3451,  2.3521],
         ...,
         [-0.5139, -1.3073, -0.3520],
         [ 0.3157,  0.0709, -1.0721],
         [-1.0015, -1.0747,  0.8050]],

        [[-0.2560,  0.2813, -0.6852],
         [ 1.5287, -0.1036, -0.1797],
         [ 2.2676, -1.0159, -0.0343],
         ...,
         [-0.8339, -0.3346,  1.2149],
         [ 0.6333,  1.5378, -0.8904],
         [ 0.8921, -0.9709,  0.8398]],

        ...,

        [[-1.5140, -0.4512, -0.6039],
         [-1.6096,  0.3659, -0.9613],
         [ 0.3391,  0.4107,  1.0604],
         ...,
         [ 0.8953, -0.9232,  1.4606],
         [ 0.0872, -2.0752,  1.2227],
         [ 0.3327,  0.5736,  0.1353]],

        [[

In [14]:
random_tensor.shape

torch.Size([224, 224, 3])

In [15]:
random_tensor.ndim

3

In [16]:
x=torch.rand(size=(4,2,3))

In [17]:
x

tensor([[[0.7311, 0.8488, 0.2382],
         [0.4384, 0.4854, 0.6286]],

        [[0.4556, 0.8576, 0.8475],
         [0.8822, 0.6900, 0.8776]],

        [[0.5559, 0.0168, 0.9811],
         [0.9955, 0.2556, 0.0582]],

        [[0.8457, 0.4936, 0.0551],
         [0.1782, 0.1208, 0.0623]]])

In [18]:
x.shape

torch.Size([4, 2, 3])