In [1]:
#!pip install torch torchvision

In [2]:
import torch
import numpy as np

In [3]:
# pythorch datatypes - tensor 


In [4]:
torch.tensor(10)

tensor(10)

In [5]:
torch.tensor([10,20,30])

tensor([10, 20, 30])

In [6]:
scalar = torch.tensor(20)

In [7]:
scalar

tensor(20)

In [8]:
type(scalar)

torch.Tensor

In [9]:
scalar + 5

tensor(25)

In [10]:
scalar - 5

tensor(15)

In [11]:
scalar * 2 

tensor(40)

In [12]:
scalar / 2

tensor(10.)

In [13]:
# kaç boyutlu olduğunu gösterir

In [14]:
scalar.dim()

0

In [15]:
scalar.shape

torch.Size([])

In [16]:
scalar.item()

20

In [17]:
type(scalar.item())

int

In [18]:
numpy_int = np.int32(20)

In [19]:
numpy_int

np.int32(20)

In [20]:
numpy_int + 10

np.int32(30)

In [21]:
scalar_from_numpy = torch.tensor(numpy_int)

In [22]:
scalar_from_numpy

tensor(20, dtype=torch.int32)

In [23]:
new_scalar = torch.tensor(30, dtype=torch.int32)

In [24]:
new_scalar

tensor(30, dtype=torch.int32)

In [25]:
tensor_float = torch.tensor(3.14)

In [26]:
tensor_float

tensor(3.1400)

In [27]:
tensor_float.dtype

torch.float32

In [28]:
tensor_float_64 = torch.tensor(3.14 , dtype = torch.float64)

In [29]:
tensor_float_64

tensor(3.1400, dtype=torch.float64)

In [30]:
tensor_float_64 * 2

tensor(6.2800, dtype=torch.float64)

In [31]:
vector = torch.tensor([10,20,30])

In [32]:
vector


tensor([10, 20, 30])

In [33]:
vector.dim()

1

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([3])

In [36]:
# count #of [ -> dimesion
# count elements -> shape 

In [37]:
matrix = torch.tensor([[10,20],[30,40]])

In [38]:
matrix

tensor([[10, 20],
        [30, 40]])

In [39]:
matrix.dim()

2

In [40]:
matrix.shape

torch.Size([2, 2])

In [41]:
tensor_example = torch.tensor([[[10,20,30],[40,50,60],[70,80,90]]])

In [42]:
tensor_example

tensor([[[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])

In [43]:
tensor_example.dim()

3

In [44]:
tensor_example.shape

torch.Size([1, 3, 3])

In [48]:
float_tensor = torch.tensor([3.0,4.0,5.0],dtype=None , 
                           device=None,#cpu gpu 
                           requires_grad=False,#whether the model learns or not
                           )

In [49]:
float_tensor.dtype

torch.float32